# Generated by Django 3.1.4 on 2020-12-28 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pnr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_id', models.CharField(max_length=30, verbose_name='transaction id')),
                ('transaction_log', models.TextField(verbose_name='transaction log')),
                ('total_amt', models.FloatField(verbose_name='total amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('pnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_pnr_id', to='pnr.pnr', verbose_name='pnr id')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'db_table': 'payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('card_type', models.CharField(max_length=50, verbose_name='card type')),
                ('store_amount', models.FloatField(verbose_name='store amount')),
                ('card_no', models.CharField(max_length=80, verbose_name='card no')),
                ('bank_tran_id', models.CharField(max_length=80, verbose_name='bank transaction id')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='status')),
                ('tran_date', models.DateTimeField(auto_now_add=True, verbose_name='transaction date')),
                ('currency', models.CharField(max_length=3, verbose_name='currency')),
                ('card_issuer', models.CharField(blank=True, max_length=50, null=True, verbose_name='card issuer')),
                ('card_brand', models.CharField(blank=True, max_length=30, null=True, verbose_name='card brand')),
                ('card_issuer_country', models.CharField(blank=True, max_length=50, null=True, verbose_name='card issuer country')),
                ('card_issuer_country_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='card issuer country code')),
                ('store_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='store id')),
                ('verify_sign', models.CharField(blank=True, max_length=255, null=True, verbose_name='verify sign')),
                ('verify_key', models.TextField(verbose_name='verify key')),
                ('cus_fax', models.CharField(blank=True, max_length=50, null=True, verbose_name='cus fax')),
                ('currency_type', models.CharField(max_length=50, verbose_name='currency type')),
                ('currency_amount', models.FloatField(blank=True, null=True, verbose_name='currency amount')),
                ('currency_rate', models.FloatField(blank=True, null=True, verbose_name='currency rate')),
                ('base_fair', models.FloatField(blank=True, null=True, verbose_name='base fair')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details_payment_id', to='payment.payment', verbose_name='payment_id')),
            ],
            options={
                'verbose_name': 'payment details',
                'verbose_name_plural': 'payment details list',
                'db_table': 'payment_details',
                'ordering': ['-created_at'],
            },
        ),
    ]
