# Generated by Django 3.1.4 on 2021-01-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_pnr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='tran_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='transaction id'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_log',
            field=models.TextField(blank=True, null=True, verbose_name='transaction log'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='bank_tran_id',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='bank transaction id'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='card_no',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='card no'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='card_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='card type'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='currency_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='currency type'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='store_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='store amount'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='tran_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='transaction date'),
        ),
    ]
