# Generated by Django 3.1.4 on 2021-01-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20210128_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='verify_key',
            field=models.TextField(blank=True, null=True, verbose_name='verify key'),
        ),
    ]
