# Generated by Django 3.1.4 on 2021-01-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20210128_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='tran_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='transaction id'),
        ),
    ]
