# Generated by Django 3.1.4 on 2021-01-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20210130_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='total_amt',
        ),
    ]
