# Generated by Django 3.1.4 on 2021-01-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_payment_total_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='tran_id',
            field=models.CharField(max_length=255, verbose_name='transaction id'),
        ),
    ]
