# Generated by Django 3.1.4 on 2021-02-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20210130_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user_email',
            field=models.EmailField(default='testuser@user.com', max_length=254, verbose_name='user email'),
            preserve_default=False,
        ),
    ]
