# Generated by Django 3.1.4 on 2020-12-28 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PNR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr_no', models.CharField(max_length=23, verbose_name='pnr no')),
                ('is_production', models.BooleanField(verbose_name='is production')),
                ('route_1_origin_location_code', models.CharField(max_length=5, verbose_name='route 1 origin location code')),
                ('route_1_destination_location_code', models.CharField(max_length=5, verbose_name='route 1 destination location code')),
                ('route_1_departure_date', models.DateTimeField(verbose_name='route 1 departure date')),
                ('route_2_origin_location_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='route 2 origin location code')),
                ('route_2_destination_location_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='route 2 destination location code')),
                ('route_2_departure_date', models.DateTimeField(blank=True, null=True, verbose_name='route 2 departure date')),
                ('route_3_origin_location_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='route 3 origin location code')),
                ('route_3_destination_location_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='route 3 destination location code')),
                ('route_3_departure_date', models.DateTimeField(blank=True, null=True, verbose_name='route 3 departure date')),
                ('route_4_origin_location_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='route 4 origin location code')),
                ('route_4_destination_location_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='route 4 destination location code')),
                ('route_4_departure_date', models.DateTimeField(blank=True, null=True, verbose_name='route 4 departure date')),
                ('cabin_class', models.CharField(blank=True, max_length=23, null=True, verbose_name='cabin class')),
                ('total_amount', models.FloatField(verbose_name='total amount')),
                ('currency', models.CharField(blank=True, max_length=7, null=True, verbose_name='currency')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnr_user_id', to='user.skytripuser', verbose_name='user id')),
            ],
            options={
                'verbose_name': 'pnr',
                'verbose_name_plural': 'pnrs',
                'db_table': 'pnr',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PnrDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name_number', models.CharField(max_length=10, verbose_name='passenger name number')),
                ('passenger_given_name', models.CharField(max_length=70, verbose_name='passenger given name')),
                ('passenger_surname', models.CharField(max_length=70, verbose_name='passenger surname')),
                ('passenger_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='passenger email')),
                ('passenger_contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='passenger contact')),
                ('passenger_dob', models.DateField(verbose_name='passenger dob')),
                ('passenger_gender', models.CharField(max_length=7, verbose_name='passenger gender')),
                ('passenger_type', models.CharField(max_length=23, verbose_name='passenger type')),
                ('passport_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='passport number')),
                ('passport_issuing_country', models.CharField(blank=True, max_length=90, null=True, verbose_name='passport issuing country')),
                ('passport_nationality_country', models.CharField(blank=True, max_length=90, null=True, verbose_name='passport nationality country')),
                ('passport_expiration_date', models.DateField(blank=True, null=True, verbose_name='passport expiration date')),
                ('visa_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='visa number')),
                ('visa_applicable_country', models.CharField(blank=True, max_length=90, null=True, verbose_name='visa applicable country')),
                ('visa_place_of_birth', models.CharField(blank=True, max_length=255, null=True, verbose_name='visa place of birth')),
                ('visa_place_of_issue', models.CharField(blank=True, max_length=255, null=True, verbose_name='visa place of issue')),
                ('visa_issue_date', models.DateField(blank=True, null=True, verbose_name='visa issue date')),
                ('visa_expiration_date', models.DateField(blank=True, null=True, verbose_name='visa expiration date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('pnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnr_details_pnr_id', to='pnr.pnr', verbose_name='pnr id')),
            ],
            options={
                'verbose_name': 'pnr details',
                'verbose_name_plural': 'pnr details list',
                'db_table': 'pnr_details',
                'ordering': ['-created_at'],
            },
        ),
    ]
