# Generated by Django 3.1.4 on 2021-01-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnr',
            name='is_ticketed',
            field=models.BooleanField(default=False, verbose_name='is ticketed'),
        ),
    ]
