# Generated by Django 3.1.4 on 2021-01-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnr', '0005_auto_20210114_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnr',
            name='data_source',
            field=models.CharField(choices=[('B2C', 'B2C'), ('B2B_AGENT', 'B2B_AGENT'), ('B2B_ADMIN', 'B2B_ADMIN')], max_length=20, verbose_name='data source'),
        ),
    ]
