# Generated by Django 3.1.4 on 2021-01-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnr', '0006_auto_20210114_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnr',
            name='sabre_token',
            field=models.TextField(default={'access_token': 'T1RLAQIpXbFS/bvTCZf87YXue4BR2bN7GBDXMuKTCsafbjLDsFnZRYRkAADAjMhAlX7ii5OkzyAW8/pQfF+FD6WYm10qBT1DaKS5j11bD9SIED7ZEDFUKuEW+1zLZhC+73PD2VpkHD+0sBABBU7js19KajOlz1IHXTQy0TMx98RYJMcDAu8z5lceHx1psEdlJdbgX3G3sNqH8GnI+VNbjpOj4BDUTAKmLYfHKB4CvptoV5bXp4mLrHud4ORJsMictwzIysJMVD/VOSgXYxTDUvWW/sjMOTD0ZjfjXSXVvW+MqdZeog6Am8sqT51r', 'expires': 1611643991.5994878, 'expires_in': 604800, 'token_type': 'bearer'}, verbose_name='sabre token'),
        ),
    ]
