# Generated by Django 3.1.4 on 2021-01-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnr', '0007_pnr_sabre_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnr',
            name='sabre_token',
            field=models.TextField(verbose_name='sabre token'),
        ),
    ]
