# Generated by Django 3.1.4 on 2021-01-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pnr', '0009_auto_20210119_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pnr',
            name='sabre_token',
        ),
    ]
