# Generated by Django 3.1.4 on 2021-01-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnr', '0011_pnr_sabre_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnr',
            name='sabre_token',
            field=models.JSONField(verbose_name='sabre token'),
        ),
    ]
