# Generated by Django 3.1.4 on 2021-01-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnr', '0015_remove_pnr_sabre_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnr',
            name='sabre_token',
            field=models.JSONField(default={}, verbose_name='sabre token'),
        ),
    ]
