# Generated by Django 3.1.4 on 2021-01-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnr', '0016_pnr_sabre_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnr',
            name='utils',
            field=models.JSONField(default=dict, verbose_name='utils'),
        ),
        migrations.AlterField(
            model_name='pnr',
            name='sabre_token',
            field=models.JSONField(default=dict, verbose_name='sabre token'),
        ),
    ]
