# Generated by Django 3.1.4 on 2021-01-28 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_pnr'),
        ('pnr', '0017_auto_20210128_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnr',
            name='payment',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='payment_pnr', to='payment.payment', verbose_name='payment'),
            preserve_default=False,
        ),
    ]
