# Generated by Django 3.1.4 on 2021-01-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnr', '0018_pnr_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnr',
            name='total_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='total amount'),
        ),
        migrations.AlterField(
            model_name='pnr',
            name='utils',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='utils'),
        ),
    ]
