# Generated by Django 3.1.4 on 2021-02-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnr', '0020_auto_20210128_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnr',
            name='carrier_code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='carrier code'),
        ),
    ]
