# Generated by Django 3.1.4 on 2021-02-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnr', '0021_pnr_carrier_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pnr',
            name='flight_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='flight number'),
        ),
    ]
