# Generated by Django 3.1.4 on 2021-02-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnr', '0022_pnr_flight_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PNRcarrierCodeStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_code', models.CharField(max_length=3, unique=True, verbose_name='carrier code')),
                ('number_of_pnrs', models.IntegerField(default=1, verbose_name='number of pnrs')),
                ('pnr_list', models.JSONField(blank=True, default=list, null=True, verbose_name='pnr list')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'pnr carrier code statistic',
                'verbose_name_plural': 'pnr carrier code statistics',
                'db_table': 'pnr_carrier_code_stats',
                'ordering': ['-updated_at'],
            },
        ),
    ]
