# Generated by Django 3.1.4 on 2021-02-11 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pnr', '0023_pnrcarriercodestats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pnrcarriercodestats',
            options={'ordering': ['-created_at'], 'verbose_name': 'pnr carrier code statistic', 'verbose_name_plural': 'pnr carrier code statistics'},
        ),
        migrations.RemoveField(
            model_name='pnrcarriercodestats',
            name='updated_at',
        ),
    ]
