# Generated by Django 3.1.4 on 2021-01-18 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pnr', '0006_auto_20210114_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('pnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_ticket_pnr', to='pnr.pnr', verbose_name='PNR')),
            ],
            options={
                'verbose_name': 'ticket issue',
                'verbose_name_plural': 'isseued tickets',
                'db_table': 'ticket_issue',
                'ordering': ['-created_at'],
            },
        ),
    ]
