# Generated by Django 3.1.4 on 2021-02-17 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnr', '0027_auto_20210214_1644'),
        ('ticket_issue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketissue',
            name='pnr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='issue_ticket_pnr', to='pnr.pnr', verbose_name='PNR'),
        ),
    ]
