# Generated by Django 3.1.4 on 2021-03-03 13:30

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import util.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=255, verbose_name='application name')),
                ('application_domain_url', models.URLField(verbose_name='application domain url')),
                ('is_production', models.BooleanField(default=False, verbose_name='is prodcution')),
                ('facebook_app_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='facebook app id')),
                ('google_client_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='google client id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Application Setting',
                'verbose_name_plural': 'Application Settings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255, verbose_name='package name')),
                ('offer_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='offer rate')),
                ('num_of_days', models.SmallIntegerField(blank=True, null=True, verbose_name='num of days')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='amount')),
                ('cut_off_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='cut off amount')),
                ('image', models.ImageField(blank=True, null=True, upload_to=util.utils.upload_package_image_path, verbose_name='image')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='summary')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Package Information',
                'verbose_name_plural': 'Package Information',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisaInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, verbose_name='code')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('information', models.TextField(blank=True, null=True, verbose_name='information')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_information_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'Visa Information',
                'verbose_name_plural': 'Visa Information',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SSLcommerzConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=100, verbose_name='store id')),
                ('store_password', models.CharField(max_length=100, verbose_name='store password')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_commerz_conf_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'SSL Commerz Conf',
                'verbose_name_plural': 'SSL Commerz Confs',
                'ordering': ['-created_at'],
            },
        ),
    ]
