# Generated by Django 3.1.4 on 2021-03-03 18:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_auto_20210303_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageinformation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='packageinformation',
            name='cut_off_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='cut off amount'),
        ),
        migrations.AlterField(
            model_name='packageinformation',
            name='offer_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='offer rate'),
        ),
    ]
