# Generated by Django 3.1.4 on 2021-03-10 13:56

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_applicationsetting_skytrip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_location_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='origin location code')),
                ('destination_location_code', models.CharField(blank=True, max_length=7, null=True, verbose_name='destination location code')),
                ('all_route', models.BooleanField(default=False, verbose_name='for all routes')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='coupon code')),
                ('cut_off_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='cut off value')),
                ('coupon_type', models.SmallIntegerField(choices=[('0', 'Percentage'), ('1', 'Fixed Amount')], default=0, max_length=1, verbose_name='coupon type')),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='max value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Coupon Setting',
                'verbose_name_plural': 'Coupon Settings',
                'ordering': ['-created_at'],
            },
        ),
    ]
