# Generated by Django 3.1.4 on 2021-03-10 16:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_auto_20210310_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponsetting',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='max value'),
        ),
    ]
