# Generated by Django 3.1.4 on 2020-12-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Do Not Mention')], default='U', max_length=10, null=True, verbose_name='gender'),
        ),
    ]
