# Generated by Django 3.1.4 on 2021-01-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201230_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Do Not Mention')], default=None, max_length=10, null=True, verbose_name='gender'),
        ),
    ]
