# Generated by Django 3.1.4 on 2020-12-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkytripUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='user id')),
                ('name', models.CharField(max_length=70, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='ip address')),
                ('mac_address', models.CharField(blank=True, max_length=20, null=True, verbose_name='mac address')),
                ('fb_token', models.TextField(blank=True, null=True, verbose_name='facebook token')),
                ('google_token', models.TextField(blank=True, null=True, verbose_name='google token')),
                ('user_status', models.SmallIntegerField(blank=True, null=True, verbose_name='user status')),
                ('user_level', models.IntegerField(blank=True, null=True, verbose_name='user level')),
                ('login_with', models.SmallIntegerField(blank=True, null=True, verbose_name='login with')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'skytrip_user',
                'ordering': ['-date_joined'],
            },
        ),
    ]
