# Generated by Django 3.1.4 on 2021-01-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skytripuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'skytrip user', 'verbose_name_plural': 'skytrip users'},
        ),
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_category', models.CharField(max_length=100, verbose_name='media category')),
                ('media_s3_url', models.URLField(verbose_name='media s3 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skytrip_user', to='user.skytripuser', verbose_name='user')),
            ],
            options={
                'verbose_name': 'user media',
                'verbose_name_plural': 'user medias',
                'ordering': ['-created_at'],
            },
        ),
    ]
