# Generated by Django 3.1.4 on 2021-01-21 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210121_1315'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermedia',
            table='user_media',
        ),
    ]
